Muchos modelos en la física, medicina y biología involucran el calculo de matrices e incluso métodos propios de la teoría del análisis numérico requieren del calculo de matrices.

Recordemos que una matriz es una arreglo bidimensional de números (reales o complejos)
$\mathbb{K} = \mathbb{R}$ o $\mathbb{C}$
$${\displaystyle \mathbf {A} = {\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{bmatrix}}}$$

cuyos elementos de la matiz son $a_{i,j}$ con $1 \leq i \leq m$ y $1 \leq j \leq n$ 

Al conjunto de las matrices de $m\times n$ lo denotamos por $\mathcal{M}_{m\times n}(\mathbb{K})$, podemos definir las siguientes opearaciones

* $+:\mathcal{M}_{m\times n}(\mathbb{K}) \times \mathcal{M}_{m\times n}(\mathbb{K}) \longrightarrow \mathcal{M}_{m\times n} (\mathbb{K})$ tal que $(A,B)\mapsto C=A+B$, es decir $c_{i,j} = a_{i,j} + b_{i,j}$

* $\mu:\mathbb{K} \times \mathcal{M}_{m\times n}(\mathbb{K}) \longrightarrow \mathcal{M}_{m\times n} (\mathbb{K})$ tal que $(\lambda,A)\mapsto B= \lambda A$, es decir $b_{i,j} = \lambda a_{i,j}$

* Muestre que $\mathcal{M}_{m\times n}(\mathbb{K})$ es un espacio vectorial sobre $\mathbb{K}$ con la suma y multiplicación escalar definidas 

Muchos problemas de diferentes diciplinas pueden ser formuladas usando matrices, ejemplo de ello es estudiar el espectro vibración de una molécula con $n$ grados de libertad vibracionale. Una primera aproximación es investigar las oscilaciones armónicas del sistema mediante la expansión de la energía potencial hasta el segundo orden de las coordenadas generalizadas alrededor de la estructura de equilibrio.  Entonces tenemos la energía potencial 

Cuyo problema se traduce a encontrar los valores y vectores propios del siguiente problema

$${\displaystyle {\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\cdots &a_{nn}\\\end{bmatrix}}  
{\begin{bmatrix}x_{1} \\x_{2}\\\vdots\\x_{n}
\\\end{bmatrix}}} = \lambda {\begin{bmatrix}m_{11}&m_{12}&\cdots &m_{1n}\\m_{21}&m_{22}&\cdots &m_{2n}\\\vdots &\vdots &\ddots &\vdots \\m_{n1}&m_{n2}&\cdots &m_{nn}\\\end{bmatrix}}  
{\begin{bmatrix}x_{1} \\x_{2}\\\vdots\\x_{n}
\\\end{bmatrix}}$$

Es decir $$\mathbf{Ax} = \lambda \mathbf{Mx}$$

Por lo que en este notebook daremos una breve introducción a los métodos numérico matriciales de algebra lineal, además de usar una paquetería de algebra lineal de python

* ¿Cómo podemos definir una matriz de $n\times m$ en partícular una matriz de $2\times 3$? 

In [1]:
M = [[2.0, 4.0, 3.0], [1.0, 5.5, 5.0]]

In [2]:
M[1][1]

5.5

Como podemos definir la suma de matrices

In [3]:
N = [[7.0, 4.5, 5.2], [5.0, 5.4, 6.4]]

In [4]:
type(N)

list

In [5]:
M + N

[[2.0, 4.0, 3.0], [1.0, 5.5, 5.0], [7.0, 4.5, 5.2], [5.0, 5.4, 6.4]]

In [6]:
4*N

[[7.0, 4.5, 5.2],
 [5.0, 5.4, 6.4],
 [7.0, 4.5, 5.2],
 [5.0, 5.4, 6.4],
 [7.0, 4.5, 5.2],
 [5.0, 5.4, 6.4],
 [7.0, 4.5, 5.2],
 [5.0, 5.4, 6.4]]

In [7]:
def sumamatrices(x,y):
    i = 0
    suma = []
    while i < len(x):
        j=0
        renglon = []
        while j < len(x[0]):
            c = x[i][j] + y[i][j]
            renglon.append(c)
            j +=1
        suma.append(renglon)
        i+=1    
    return suma

In [8]:
R=sumamatrices(M, N)

In [9]:
R

[[9.0, 8.5, 8.2], [6.0, 10.9, 11.4]]

In [10]:
def multiplicacion(l,x):
    i=0
    multi = []
    while i < len(x):
        j=0
        renglon = []
        while j < len(x[0]):
            c = l*x[i][j]
            renglon.append(c)
            j+=1
        i+=1
        multi.append(renglon)
            
    return multi

In [11]:
multiplicacion(2.5,R)

[[22.5, 21.25, 20.5], [15.0, 27.25, 28.5]]

Sabemos que la transpuesta de una matriz por definición es $a_{i,j} = a_{j,i}$

In [19]:
def transMatriz(x):
    newmatrix = []
    for i in range(len(x[0])):
        row = []
        for j in range(len(x)):
            anew = x[j][i]
            row.append(anew)
        newmatrix.append(row)
    return newmatrix

In [20]:
A = [[7.0, 4.5, 5.2, 8], [5.0, 5.4, 6.4, 56]]

In [24]:
B = transMatriz(A)
B

[[7.0, 5.0], [4.5, 5.4], [5.2, 6.4], [8, 56]]

In [27]:
7.0*7 + 4.5*4.5 + 5.2*5.2 + 8.*8. 

160.29000000000002

Ahora definimos el producto de dos matrices, el cual es, para las matices $A_{n\times m}$ y $B_{m\times r}$ es $c_{i,j} = \displaystyle \sum _{k=1} ^{m} = a_{i,k}b_{k,j}$

In [22]:
def productoMatriz(x,y):
    produc =  []
    for i in range(len(x)):
        row = []
        for j in range(len(y[0])):
            aux = 0
            for k in range(len(x[0])):
                aux = aux + x[i][k]*y[k][j]
            row.append(aux)
        produc.append(row)
    return produc

In [25]:
P = productoMatriz(A, B)

In [26]:
P

[[160.29000000000002, 540.58], [540.58, 3231.12]]

Vemos que podemos sumar matrices con `numpy`

In [28]:
from numpy import *
#from scipy.linalg import *

Pero pytho ya tiene una librería de álgebra lineal, `scipy.linalg`

In [31]:
a = matrix(A)
b = matrix(B)

In [32]:
n

matrix([[  7. ,   4.5,   5.2,   8. ],
        [  5. ,   5.4,   6.4,  56. ]])

In [33]:
type(n)

numpy.matrixlib.defmatrix.matrix

In [36]:
r=n + n

In [39]:
1.5*r

matrix([[  21. ,   13.5,   15.6,   24. ],
        [  15. ,   16.2,   19.2,  168. ]])

In [47]:
s = n*m - matrix([[0.0, 540.58],[0.0, 0.0]])
s

matrix([[  160.29,     0.  ],
        [  540.58,  3231.12]])

In [56]:
t = transpose(s)

In [57]:
linalg.det(t)

517916.22479999921

In [58]:
160.29*3231.12

517916.22479999997

In [59]:
N

[[7.0, 4.5, 5.2], [5.0, 5.4, 6.4]]

In [60]:
M

[[2.0, 4.0, 3.0], [1.0, 5.5, 5.0]]

In [61]:
n = array(N)
m = array(M)

In [62]:
n

array([[ 7. ,  4.5,  5.2],
       [ 5. ,  5.4,  6.4]])

In [63]:
r = n+m

In [64]:
r

array([[  9. ,   8.5,   8.2],
       [  6. ,  10.9,  11.4]])

In [65]:
2.5*r

array([[ 22.5 ,  21.25,  20.5 ],
       [ 15.  ,  27.25,  28.5 ]])

Definamos la multiplición de matrices

In [66]:
S = [[5, 1.5, 5], [6.0, 3.5, 0]]

In [67]:
T = [[ 5, 5, 1, 1], [6.0, 3.5, 0, 1], [0, 1, 0, 1]]

In [69]:
s, t = array(S), array(T)

In [71]:
dot(s,t)

array([[ 34.  ,  35.25,   5.  ,  11.5 ],
       [ 51.  ,  42.25,   6.  ,   9.5 ]])

In [74]:
def product(x,y):
    i=0
    prod = []
    while i < len(x):
        j =0
        renglon = []
        while j < len(y[0]):
            k = 0
            c = 0
            while k < len(y):
                aux = x[i][k] * y[k][j]
                c = c + aux
                k +=1
            renglon.append(c)
            j +=1
        prod.append(renglon)
        i +=1
    return array(prod)    

In [76]:
product(s,t)

array([[ 34.  ,  35.25,   5.  ,  11.5 ],
       [ 51.  ,  42.25,   6.  ,   9.5 ]])

De una matriz podemos calcular su determinante

Otra aplicación inmediata de matrices es resolver sistemas de ecuaciones, por ejemplo:

\begin{align}
a_{11}x_{1} + a_{12}x_2 + \cdots + a_{1n}x_{n} &= b_1 \\
a_{21}x_{1} + a_{22}x_2 + \cdots + a_{2n}x_{n} &= b_2 \\
 \vdots \\
a_{m1}x_{1} + a_{m2}x_2 + \cdots + a_{mn}x_{n} &= b_m
\end{align}

donde $x_i$ son la incoignitas, $a_{ij}$ y $b_i$ son constantes

De nuestro curso de álgebra sabemos que tenemos tres posibilidades

* La solución es única. Esto es existe un y sólo un conjunto de valores que satisface el sistema
* No tiene solución. No existe un conjunto de $x$ talque satisfaga el sistema.
* Se tiene un infinidad de solucines. El conjunto de $x$ que satisface el sistema es infinito

El sistema anterior lo podemos escribir como:

$${\displaystyle {\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\cdots &a_{nn}\\\end{bmatrix}}  
{\begin{bmatrix}x_{1} \\x_{2}\\\vdots\\x_{n}
\\\end{bmatrix}}} =   {\begin{bmatrix}b_{1} \\b_{2}\\\vdots\\b_{n}
\\\end{bmatrix}}$$

Esto se puede escribir como $\mathbf{A} \mathbf{x} = \mathbf{b}$, con $\mathbf{A} \in \mathcal{M}_{nn}(\mathbb{K})$. Sabemos que para la solución sea única se debe cumplir que $n=m$ y además $\mathbf{A}$ debe ser invertible y así obtener $\mathbf{A}^{-1}\mathbf{A} \mathbf{x} = \mathbf{A}^{-1}\mathbf{b} \Longrightarrow  \mathbf{x} = \mathbf{A}^{-1}\mathbf{b} = \mathbf{B} $

Para resolver este problema hay mucha teoría de análisis numérico, pero ahora daremos un enorme paso y usaremos las paquetería de python ya implementadas, pero sería muy importamte que el estudiante apele a su invaluable curiosidad e investigue detalladamente la parte formal de cada uno de los métodos, un texto que le podría ayudar es *"Matrix Analsys and Applied Linear Algebra"* de **Carl D. Meyer**

Ahora importemos `scipy.linalg`

In [77]:
from scipy.linalg import *

Y consideremos el siguiente ejemplo 

\begin{align}
3x + 2y + z & = 39  \\
2x + 3y + z & = 34  \\
x + 2y + 3z & = 26
\end{align}

Cuya matriz asociada es

In [78]:
a = array([[3., 2., 1.], [2., 3., 1.], [1., 2., 3.]])

In [79]:
a

array([[ 3.,  2.,  1.],
       [ 2.,  3.,  1.],
       [ 1.,  2.,  3.]])

Calculemos su inversa, sabemos que una matriz tiene inversa si el determinante es distinto de cero, entonces calculemos el determinante de $\mathbf{A}$ y para ello usamos la función `det(A)`

In [80]:
det(a)

12.0

Como el determinante de la matriz no es cero podemos calcular su inversa, `scipy` cuenta con una función llamada `inv()` que calcula la inversa de dicha matriz

In [81]:
ainv = inv(a)

In [82]:
ainv

array([[ 0.58333333, -0.33333333, -0.08333333],
       [-0.41666667,  0.66666667, -0.08333333],
       [ 0.08333333, -0.33333333,  0.41666667]])

Veamos si efectivamente esta es la inversa 

In [85]:
dot(ainv,a)

array([[  1.00000000e+00,  -8.32667268e-17,  -5.55111512e-17],
       [ -8.32667268e-17,   1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.11022302e-16,   1.00000000e+00]])

In [86]:
product(a,ainv)

array([[  1.00000000e+00,  -1.11022302e-16,   0.00000000e+00],
       [ -1.24900090e-16,   1.00000000e+00,   5.55111512e-17],
       [  5.55111512e-17,   0.00000000e+00,   1.00000000e+00]])

Ahora definamos el vector $\mathbf{b}$

In [87]:
b = array([39., 34., 26.])

In [88]:
dot(ainv, b)

array([ 9.25,  4.25,  2.75])

Ahora probemos la función `solve`

In [89]:
solve(a,b)

array([ 9.25,  4.25,  2.75])